instances:
  - name: "wildcard"
    dns:
      - "*.home.io"
      - "*.example.io"
      - "*.svc.cluster.local"
      - "localhost"
    ip:
      - "0.0.0.0"
      - "127.0.0.1"
      - "192.168.49.2"
      - "192.168.1.75"
  - name: "pgadmin"
    dns:
      - "pgadmin.home.io"
      - "pgadmin.example.io"
      - "pgadmin"
      - "pgadmin.db.svc.cluster.local"
      - "*.svc.cluster.local"
      - "localhost"
    ip:
      - "0.0.0.0"
      - "127.0.0.1"
      - "192.168.49.2"
      - "192.168.1.75"
  - name: "postgres"
    dns:
      - "postgres.home.io"
      - "postgres.example.io"
      - "pg.home.io"
      - "pg.example.io"
      - "postgres"
      - "postgres.db.svc.cluster.local"
      - "postgres.default.svc.cluster.local"
      - "postgres-ext"
      - "postgres-ext.db.svc.cluster.local"
      - "postgres-ext.default.svc.cluster.local"
      - "*.svc.cluster.local"
      - "localhost"
    ip:
      - "0.0.0.0"
      - "127.0.0.1"
      - "192.168.49.2"
      - "192.168.1.75"
  - name: "api"
    dns:
      - "rust-restapi"
      - "rust-restapi.rust.svc.cluster.local"
      - "rust-restapi.db.svc.cluster.local"
      - "rust-restapi.default.svc.cluster.local"
      - "rust-restapi-ext"
      - "rust-restapi-ext.rust.svc.cluster.local"
      - "rust-restapi-ext.db.svc.cluster.local"
      - "rust-restapi-ext.default.svc.cluster.local"
      - "api1.home.io"
      - "api2.home.io"
      - "api1.example.io"
      - "api2.example.io"
      - "api1"
      - "api2"
      - "api-ext"
      - "api-ext.rust.svc.cluster.local"
      - "api-ext.db.svc.cluster.local"
      - "api-ext.default.svc.cluster.local"
      - "*.svc.cluster.local"
      - "localhost"
    ip:
      - "0.0.0.0"
      - "127.0.0.1"
      - "192.168.49.2"
      - "192.168.1.75"
