instances:
  - name: "wildcard"
    dns:
      - "*.home.io"
      - "*.example.io"
      - "*.svc.cluster.local"
      - "localhost"
    ip:
      - "0.0.0.0"
      - "127.0.0.1"
      - "192.168.1.75"
  - name: "pgadmin"
    dns:
      - "pgadmin.home.io"
      - "pgadmin.example.io"
      - "pgadmin"
      - "pgadmin.db.svc.cluster.local"
      - "localhost"
    ip:
      - "0.0.0.0"
      - "127.0.0.1"
      - "192.168.1.75"
  - name: "postgres"
    dns:
      - "postgres.home.io"
      - "postgres.example.io"
      - "pg.home.io"
      - "pg.example.io"
      - "postgres"
      - "postgres.db.svc.cluster.local"
      - "localhost"
    ip:
      - "0.0.0.0"
      - "127.0.0.1"
      - "192.168.1.75"
  - name: "api"
    dns:
      - "api1.home.io"
      - "api2.home.io"
      - "api1.example.io"
      - "api2.example.io"
      - "api1"
      - "api2"
      - "localhost"
    ip:
      - "0.0.0.0"
      - "127.0.0.1"
      - "192.168.1.75"
