apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.env.name }}-{{ .Values.env.app.name }}"
  labels:
    app: "{{ .Values.env.name }}-{{ .Values.env.app.name }}"
spec:
  selector:
    app: "{{ .Values.env.name }}-{{ .Values.env.app.name }}"
  ports:
    - name: "http-{{ .Values.env.name }}-{{ .Values.env.app.name }}"
      port: {{ .Values.env.app.port }}
      protocol: TCP
      targetPort: {{ .Values.env.app.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.env.name }}-{{ .Values.env.app.name }}-ext"
  labels:
    app: "{{ .Values.env.name }}-{{ .Values.env.app.name }}"
spec:
  type: NodePort
  selector:
    app: "{{ .Values.env.name }}-{{ .Values.env.app.name }}"
  ports:
    - name: "http-{{ .Values.env.name }}-{{ .Values.env.app.name }}-ext"
      port: {{ .Values.env.app.port }}
      protocol: TCP
      targetPort: {{ .Values.env.app.port }}
      nodePort: {{ .Values.env.app.nodePort }}
{{- if .Values.service.monitor.enabled }}
---
# requires crds in the cluster
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "{{ .Values.env.name }}-{{ .Values.env.app.name }}"
  labels:
    monitoring: "{{ .Values.env.name }}-{{ .Values.env.app.name }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Values.env.name }}-{{ .Values.env.app.name }}"
  endpoints:
  - port: "http-{{ .Values.env.name }}-{{ .Values.env.app.name }}"
{{- end }}
